# Generated by Django 3.0.2 on 2020-10-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='匿名', max_length=20)),
                ('editor_Content', models.CharField(max_length=500)),
                ('times', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='1', max_length=10)),
            ],
        ),
    ]
