# Generated by Django 3.1.2 on 2020-10-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='', max_length=20)),
                ('data', models.CharField(default='', max_length=20)),
                ('my_message', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
